### ISSUE TITLE
启动报错 SyntaxError: The requested module '@vue/devtools-core' does not provide an export named 'callViteClientListener'

### ISSUE THREAD

**Issue by QiuMing** [chansee97/nova-admin#21]
### Description

* Node 版本：v20.14.0
* pnpm 版本：9.3.0
*
```
pnpm dev

> nova-admin@0.9.4 dev /Users/xpeng/Project/fuyao/nova-admin
> vite --mode dev --port 9980

failed to load config from /Users/xpeng/Project/fuyao/nova-admin/vite.config.ts
error when starting dev server:
file:///Users/xpeng/Project/fuyao/nova-admin/node_modules/.pnpm/vite-plugin-vue-devtools@7.2.1_vite@5.3.1_vue@3.4.29/node_modules/vite-plugin-vue-devtools/dist/vite.mjs:7
import { defineViteServerAction, callViteClientListener, initViteServerContext } from '@vue/devtools-core';
                                 ^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: The requested module '@vue/devtools-core' does not provide an export named 'callViteClientListener'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadConfigFromBundledFile (file:///Users/xpeng/Project/fuyao/nova-admin/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.2_sass@1.77.5/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:66913:15)
    at async loadConfigFromFile (file:///Users/xpeng/Project/fuyao/nova-admin/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.2_sass@1.77.5/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:66754:24)
    at async resolveConfig (file:///Users/xpeng/Project/fuyao/nova-admin/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.2_sass@1.77.5/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:66364:24)
    at async _createServer (file:///Users/xpeng/Project/fuyao/nova-admin/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.2_sass@1.77.5/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:62977:18)
    at async CAC.<anonymous> (file:///Users/xpeng/Project/fuyao/nova-admin/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.2_sass@1.77.5/node_modules/vite/dist/node/cli.js:735:20)
 ELIFECYCLE  Command failed with exit code 1.
```

### Expected

* 如有解决思路，请不吝给出，感谢

### Validations

- [X] Ensure this issue not a bug proposal.
- [X] Read the [docs](https://nova-admin-docs.netlify.app/).
- [X] Check that there isn't [already an issue](https://github.com/chansee97/nova-admin/issues) that descript the same thing to avoid creating a duplicate.

**Comment by chansee97** [comment]
将`build\plugins.ts`中的VueDevTools插件移除可以解决这个问题
![image](https://github.com/chansee97/nova-admin/assets/90271994/fcaef056-8dcc-4988-b742-72d706db57b8)
